run_as shiny;

preserve_logs true;

server {
  listen 3838;

  # Redirige la raíz directamente a la app sipm
  location / {
    app_dir /srv/shiny-server/sipm;
    log_dir /var/log/shiny-server;
  }
}
